/**
 * Export alert logs to CSV file
 */
export const exportAlertsToCSV = (alerts) => {
  if (!alerts || alerts.length === 0) {
    alert("No incident logs available to export.");
    return;
  }

  const headers = ["Alert ID", "Location", "Risk Level", "Risk Score", "Rainfall (mm)", "Timestamp", "Dispatched Units"];
  
  const rows = alerts.map((al) => [
    al.id,
    `"${al.location || 'N/A'}"`,
    al.level || al.type || "MODERATE",
    al.score || "N/A",
    al.rainfall || "N/A",
    `"${al.timestamp || al.createdAt || al.time || new Date().toISOString()}"`,
    `"${(al.dispatchedTo && al.dispatchedTo.join(', ')) || 'NDRF State Unit, Disaster Authority'}"`
  ]);

  const csvContent = "data:text/csv;charset=utf-8," + [headers.join(","), ...rows.map(e => e.join(","))].join("\n");
  const encodedUri = encodeURI(csvContent);
  const link = document.createElement("a");
  link.setAttribute("href", encodedUri);
  link.setAttribute("download", `Landslide_Incident_Report_${new Date().toISOString().slice(0, 10)}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

/**
 * Trigger official printable/PDF Disaster Summary Report
 */
export const printIncidentReport = (alerts) => {
  if (!alerts || alerts.length === 0) {
    alert("No incident logs available to generate report.");
    return;
  }

  const printWindow = window.open("", "_blank", "width=900,height=700");
  const tableRows = alerts.map((al) => `
    <tr>
      <td style="padding: 8px; border: 1px solid #ddd;">#${al.id}</td>
      <td style="padding: 8px; border: 1px solid #ddd;"><b>${al.location}</b></td>
      <td style="padding: 8px; border: 1px solid #ddd; color: ${al.level === 'CRITICAL' ? '#ef4444' : al.level === 'HIGH' ? '#f97316' : '#22c55e'}; font-weight: bold;">
        ${al.level || al.type}
      </td>
      <td style="padding: 8px; border: 1px solid #ddd;">${al.score || 'N/A'}/100</td>
      <td style="padding: 8px; border: 1px solid #ddd;">${al.rainfall || 'N/A'} mm</td>
      <td style="padding: 8px; border: 1px solid #ddd;">${al.timestamp || al.createdAt || al.time || 'Logged'}</td>
    </tr>
  `).join("");

  printWindow.document.write(`
    <html>
      <head>
        <title>Landslide AI - Official Incident Report</title>
        <style>
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 30px; color: #1e293b; }
          .header { border-bottom: 2px solid #0f172a; padding-bottom: 12px; margin-bottom: 20px; }
          .meta { display: flex; justify-content: space-between; margin-bottom: 20px; font-size: 13px; color: #64748b; }
          table { width: 100%; border-collapse: collapse; font-size: 13px; text-align: left; }
          th { background: #0f172a; color: #fff; padding: 10px 8px; border: 1px solid #0f172a; }
          .footer { margin-top: 30px; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 10px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h2 style="margin: 0; color: #0f172a;">LandslideAI • Official Early Warning & Incident Report</h2>
          <p style="margin: 4px 0 0; font-size: 13px; color: #64748b;">Ministry of Development of North Eastern Region (MDoNER) Automated Telemetry Log</p>
        </div>
        <div class="meta">
          <div><b>Generated On:</b> ${new Date().toLocaleString()}</div>
          <div><b>Total Incidents Logged:</b> ${alerts.length}</div>
        </div>
        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Location</th>
              <th>Severity</th>
              <th>Risk Score</th>
              <th>Rainfall</th>
              <th>Dispatch Time</th>
            </tr>
          </thead>
          <tbody>
            ${tableRows}
          </tbody>
        </table>
        <div class="footer">
          This report is auto-generated by the LandslideAI Early Warning System prototype. Validated for NDRF / SDRF emergency response protocols.
        </div>
      </body>
    </html>
  `);

  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => {
    printWindow.print();
    printWindow.close();
  }, 350);
};